### ISSUE TITLE
discrepancy between pdf and md

### ISSUE THREAD

**Issue by roedoejet** [acl-org/aclpubcheck#11]
Thanks for this!

Steps 2 and 4 in the four steps in the pdf are out of date with the readme:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/14815080/158240497-d80c92e4-c5ac-419b-899f-61e1db797b76.png">

The readme is correct and the pdf should be updated to have the same steps.

**Comment by ryancotterell** [comment]
Thanks! We're on it.

**Comment by crux82** [comment]
Fixed

**Comment by roedoejet** [comment]
Thanks, step 4 still has the erroneous underline though (or you need to add `-m` and change the command).

**Comment by crux82** [comment]
Updated! Hopefully, this is the good one! :-)
