### ISSUE TITLE
URL causes text margin error

### ISSUE THREAD

**Issue by go-inoue** [acl-org/aclpubcheck#12]
I am getting a margin error for the following latex input. Does anyone have the same issue?

```latex
The GLF data is available at \url{https://camel.abudhabi.nyu.edu/annotated-gumar-corpus/} and the LEV data is available at \url{https://portal.sina.birzeit.edu/curras/}.
```

![errors-ACL2022-page-11](https://user-images.githubusercontent.com/20531705/158385165-b1c7c489-9cb7-4822-86bf-676604419e9c.png)

**Comment by crux82** [comment]
And it is correct. If you compare with the symbol ":"  two rows later... you are (really slightly) out of the margins.

Please, fix it (e.g., by adding a newline before "The GLF data..." or an \hspace{-0.3em} before the start of the link).

Does it work?

**Comment by go-inoue** [comment]
`\hspace{-0.3em}` did not fix the margin error but adding a newline before "The GLF data..." worked (although it looks a bit ugly...). Thank you so much!

![Screen Shot 2022-03-15 at 5 32 14 PM](https://user-images.githubusercontent.com/20531705/158389544-18af477b-a636-4ee3-a1aa-6b1cbb0d1017.png)
