### ISSUE TITLE
ImageMagik issue: Convert Not Allowed

### ISSUE THREAD

**Issue by protonish** [acl-org/aclpubcheck#17]
Kept running into this issue on the lab machine. 
```
convert: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/408
```
While this not be a problem for most people, for those who do run into this issue the root cause is some security policies that ImageMagik has to limit access rights. 

The solution is pretty simple as described on [askubuntu](https://askubuntu.com/a/1127265).

**Comment by crux82** [comment]
Thank you for your suggestion.

I think this is the same issue discussed here: 

https://github.com/acl-org/aclpubcheck/issues/8
