### ISSUE TITLE
Parsing error when top margin is too small

### ISSUE THREAD

**Issue by casey-meehan** [acl-org/aclpubcheck#21]
Our paper caused a parsing error with top margins that were too small (on pages 2 and 7). As such, we could not see what the actual formatting problem was (no errors were reported for the paper, only parsing errors were reported). 

I've attached the original problematic paper (which has been fixed and uploaded) as well as the stack trace of the parser. 
[meehan_bad_margin.pdf](https://github.com/acl-org/aclpubcheck/files/8421708/meehan_bad_margin.pdf)
![meehan_colab_error](https://user-images.githubusercontent.com/31673821/161845576-f97f5c74-b264-4604-9892-51084184e842.png)

**Comment by crux82** [comment]
Thank you. 

I see that such a problem arises only on colab.
It is quite difficult to replicate on my laptop (where this error does not occur)

**Comment by crux82** [comment]
The last commit https://github.com/acl-org/aclpubcheck/commit/fef5a4635a9a277c80b7eff2f3cff42c417e1347 should correct your issue. 

Can you please confirm it and close this issue?

Thank you for your support!

**Comment by PradeepNalluri** [comment]
Hi, I am still facing the issue. I checked out commit #fef5a46 and ran the tool. The following is the error 
![image](https://user-images.githubusercontent.com/25664333/162235686-6e30063c-bdb1-46bf-b97d-591069741e06.png)

**Comment by crux82** [comment]
Can you share with me your PDF in a private message?

**Comment by PradeepNalluri** [comment]
Shared the page. T confirm the following is the stack trace
![image](https://user-images.githubusercontent.com/25664333/162239305-3597284a-0aef-4452-9fc0-a90e15dba166.png)

**Comment by crux82** [comment]
I should have fixed the issue. It was a similar bug fixed in commit https://github.com/acl-org/aclpubcheck/commit/fef5a4635a9a277c80b7eff2f3cff42c417e1347

Can I ask you to check the ill-formatted version of your paper to check it if works now?

Thanks!

**Comment by PradeepNalluri** [comment]
It's working now

![image](https://user-images.githubusercontent.com/25664333/162267632-715a1e05-ce81-486c-8b09-02f9d79c565c.png)

thanks for all your work and fix!
