### ISSUE TITLE
Pages that don't contain text cause an error 

### ISSUE THREAD

**Issue by pkavumba** [acl-org/aclpubcheck#22]
I tried to check a paper with a page containing only an image without any text, and `aclpubcheck/formatchecker.py` throws an error. This error is caused by line 400, `text = page.extract_text().split("\n")`, in `check_page_num` because `page.extract_text()` returns `None` when a page has no textual content.

><img width="956" alt="aclpaperchecker" src="https://user-images.githubusercontent.com/27487481/161899200-19d3f55c-45d6-4906-b992-17df3ed60656.png">

**Comment by crux82** [comment]
Would it be possible to share your PDF (even in a private message) to replicate the issue?

Thanks

Danilo

**Comment by pkavumba** [comment]
Sent a PM

**Comment by crux82** [comment]
I checked you case but I was not able to replicate the issue. 
Moreover, I do not see that code at line 400. 
Can you help me to find this problematic code?

**Comment by pkavumba** [comment]
I reinstalled the checker and the error didn't happen this time
