### ISSUE TITLE
Clarifications in instructions

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/aclpubcheck#3]
- The URL in the `git clone` step uses a git URL, which didn't work for me; I had to change to https.
- If you install directly from git, then the command `python3 aclpubcheck/formatchecker.py ...` won't work.
- Please explain what PAPER_TYPE is.

**Comment by ryancotterell** [comment]
Updated the instructions. What do you think? For bullet 2, I removed the direct installation as it's not useful for running the script.

**Comment by davidweichiang** [comment]
That helps (though the formatting of the double quotes is a little odd).

If you create an executable, then users will be able to use pip install directly from git, and the instructions also won't depend on them being in the correct directory.

**Comment by ryancotterell** [comment]
I fixed the double-quote formatting issue.

Can we create an executable that would also work on Windows?

**Comment by davidweichiang** [comment]
Sorry, I don't know...all the more reason to make it web-based...

**Comment by ryancotterell** [comment]
I agree. I'll close this issue and keep the web based one up.
