### ISSUE TITLE
List index out of range for one specific citation

### ISSUE THREAD

**Issue by maartjeth** [acl-org/aclpubcheck#30]
I get an index out of range error when citing a specific article (all other citations are fine):

```
@inproceedings{cao-etal-2018-retrieve,
    title = "Retrieve, Rerank and Rewrite: Soft Template Based Neural Summarization",
    author = "Cao, Ziqiang  and
      Li, Wenjie  and
      Li, Sujian  and
      Wei, Furu",
    booktitle = "Proceedings of the 56th Annual Meeting of the Association for Computational Linguistics (Volume 1: Long Papers)",
    month = jul,
    year = "2018",
    address = "Melbourne, Australia",
    publisher = "Association for Computational Linguistics",
    url = "https://aclanthology.org/P18-1015",
    doi = "10.18653/v1/P18-1015",
    pages = "152--161",
}
```

This is a snippet of the sentence in the paper: [...] Work on template-based~\cite[e.g.,][]{cao-etal-2018-retrieve} and [...]

The error is:

```
File [...]/aclpubcheck/name_check.py", line 106, in extract_names
    additional+1, new_paper_authors[additional+1])
IndexError: list index out of range
```

I did a bit of debugging and it seems that it parses the title as the authors. Line 100 in name_check.py: `new_paper_authors = [['rerank', 'Retrieve'], ['rewrite']]` (I guess the first part of the title reads as if these could be author names?)

**Comment by crux82** [comment]
I think it is related to the new function introduced by @pranav-ust

**Comment by maartjeth** [comment]
Yes, it works now, thanks! 

Closing the issue.
