### ISSUE TITLE
Is it possible to deactivate the check of names in citations

### ISSUE THREAD

**Issue by crux82** [acl-org/aclpubcheck#34]
@pranav-ust Is it possible to deactivate the check of names in citations, e.g., with a parameter --disable_name_check

This is additional check can be very useful but in some cases, only the format check can be required

**Comment by pranav-ust** [comment]
I will add this feature. But may I know in what cases name check is not required?

**Comment by crux82** [comment]
Not really clear, in fact, it should be enabled by default.

**Comment by pranav-ust** [comment]
Issue solved in #35. Please double check and close this issue.

**Comment by crux82** [comment]
@pranav-ust I checked and it works

I take this opportunity to congratulate you on the great work you have done
