### ISSUE TITLE
Warning even after correcting the bib entry

### ISSUE THREAD

**Issue by arijitthegame** [acl-org/aclpubcheck#36]
Hi, 

 Thank you for the great work. I am getting a bib warning after running the checker even though I copied the ACL bibliography by going to the appropriate website. Attached is the screenshot of the warning.
<img width="1624" alt="Screen Shot 2022-05-03 at 10 12 11 AM" src="https://user-images.githubusercontent.com/25961440/166469822-47b3a4a1-3aaf-4448-b5bc-c8c97458f117.png">

**Comment by crux82** [comment]
Maybe the software is not able to correctly parse your updated entry. 
Anyway, I think that @pranav-ust can help you. 

Bests

**Comment by pranav-ust** [comment]
I can't really fix this unless I have your PDF file.

You can ignore the warning if you have already corrected the bib. We already have a disclaimer that citation warnings can be inaccurate. Sometimes the model parses incorrectly due to text extraction from PDF.

**Comment by crux82** [comment]
@pranav-ust thank you for your quick response.

@arijitthegame please, share the pdf in a private message to @pranav-ust or please close this issue. 

Thanks!

**Comment by arijitthegame** [comment]
@pranav-ust Just emailed you. Thank once both once again for your quick responses.
