### ISSUE TITLE
Package as command-line tool

### ISSUE THREAD

**Issue by tnaumann** [acl-org/aclpubcheck#39]
Given that we're now asking authors to run this against their papers, it would be excellent to improve the accessibility of this tool. Specifically, we should aim to package as `aclpubcheck` on PyPI and add command-line entrypoints (e.g. `aclpubcheck`) so taht authors can install and run this tool against their pdf more easily.

**Comment by crux82** [comment]
It would be great. 

Unfortunately, I am not an expert in this "packaging process". 
Can you help us in this process?

Thanks!

Danilo

**Comment by crux82** [comment]
It should be solved in https://github.com/acl-org/aclpubcheck/pull/66
