### ISSUE TITLE
List of allowed fonts

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/aclpubcheck#4]
I thought an issue had been posted about this on another copy of this repo, but the formatting guidelines ask for Times, Times Roman, or even Computer Modern (!) but the checker requires NimbusRomNo9L-Regu, which is only one of many Times clones.

Another issue is that some engines prepend random letters to the font name. For example, my paper uses IIKZFC+TeXGyreTermesX-Regular.

**Comment by ryancotterell** [comment]
Does this throw an error on your paper?

**Comment by davidweichiang** [comment]
Yes

**Comment by ryancotterell** [comment]
The prepending shouldn't matter, I don't think. We only care about the end. Can you add your font to https://github.com/acl-org/aclpubcheck/blob/main/aclpubcheck/formatchecker.py#L242? I made the data structure a set so we can enumerate the most common ones.
