### ISSUE TITLE
default instructions PDF generates 191 errors

### ISSUE THREAD

**Issue by kawine** [acl-org/aclpubcheck#43]
The default "Instructions for EMNLP 2022" pdf, generated using the suggested EMNLP latex files, yield 191 errors, which are of the form: 

Error (Margin): Text on page 1 bleeds into the left margin.
Error (Margin): Text on page 1 bleeds into the right margin.
Error (Margin): Text on page 2 bleeds into the left margin.
Error (Margin): Text on page 2 bleeds into the right margin.
Error (Margin): Text on page 3 bleeds into the left margin.
Error (Margin): Text on page 3 bleeds into the right margin.

**Comment by ryancotterell** [comment]
I think this is due to the line numbers, right? I guess we should try to build a work-around for non-CR papers.

**Comment by crux82** [comment]
Sorry but I do not understand.

@kawine are you using a tool for checking camera ready papers ti check a pre camera ready format? (i.e., with the row numbers made visibile)

In this case I think It Is normal to have these errors.

Can you clarify your question, please?

**Comment by kawine** [comment]
Yes the line numbers seem to be the issue. It'd be helpful to add a comment to the README instructing people to use the de-anonymized version of the paper.
