### ISSUE TITLE
Getting margin violations for line numbers when checking a PDF created with [review]{ACL2023}

### ISSUE THREAD

**Issue by KathyHaem** [acl-org/aclpubcheck#49]
As it says in the title, I get outputs like this
```
Found text violation: Margin.LEFT      {'text': '001', 'x0': 12.217, 'x1': 25.511.., ...}
```
for every single line number in the review version. Is this not meant to be used for checking the review version?

I am using the current ACL2023 style files/template for the PDF; did not check the issue on other template versions. I'm running aclpubcheck from the colab notebook due to #24 

Thanks for any pointers!

**Comment by crux82** [comment]
Hi, I think you are using the PDF version containing the number of lines for the review. Aclpubcheck works with camera ready versions. 

What do you have in the latex file?
Please try uncommenting 

```
% Remove the "review" option to generate the final version.
%\usepackage[review]{acl}
```

**Comment by KathyHaem** [comment]
Thanks for the prompt response. This is a misunderstanding then, as the CFP on the ACL page includes this: "We recommend using the [ACL Pubcheck tool](https://github.com/acl-org/aclpubcheck) to confirm that your submission conforms to the standards prior to submission, so as to avoid desk rejections."

**Comment by crux82** [comment]
I imagine it was referred to as the camera ready. Anyway, if you compiled as a camera ready and aclpubcheck works, please close this issue. 

Bests

Danilo

**Comment by jakpra** [comment]
I agree with @KathyHaem that the aclpubcheck instructions are misleading here:

> We highly recommend running ACL pubcheck on your papers pre-submission—a well formatted paper helps keep the reviewers focused on the scientific content.

To be fair, the instruction text then also specifies that the *main purpose* is to ensure correct formatting of accepted papers (i.e., camera-readys).

However, if pre-submission check is one of the intended uses and this is even stated in the CfP for avoidance of desk rejection(!!!), it would indeed be nice to either have a mode that ignores line numbers, or explicitly say in the instructions that it needs to be the non-review PDF.
