### ISSUE TITLE
Web-based version

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/aclpubcheck#5]
It may be difficult or inconvenient for some users to clone a git repo and run a Python script from the command-line, especially Windows users using Overleaf. A web-based version would be a lot more convenient -- is that in the works?

**Comment by ryancotterell** [comment]
I think we can put this in the pipeline. I've sent a note in our Slack.

**Comment by ryancotterell** [comment]
We now have a CodaLab version https://colab.research.google.com/drive/1Sq6ilmrFUQpUFMkV71U8-Wf0madW-Uer?usp=sharing.
