### ISSUE TITLE
The online tool reports margin errors for the ACL 2023 official instruction pdf.

### ISSUE THREAD

**Issue by snowood1** [acl-org/aclpubcheck#52]
![image](https://user-images.githubusercontent.com/26472618/209846078-bb1c44da-fd8f-4bab-9117-00705a63e5a7.png)

**Comment by ryancotterell** [comment]
I think it's picking up on the margin numbers. Can you turn them off and
try again?

**Comment by snowood1** [comment]
Thanks. It shows all clear after removing the "reviews" option.
