### ISSUE TITLE
No such file or directory: '/etc/ImageMagick-6/policy.xml

### ISSUE THREAD

**Issue by dadelani** [acl-org/aclpubcheck#55]
hi,

I'm having the error below when using ACL pubcheck on Google colab:FileNotFoundError  

  Traceback (most recent call last)
[<ipython-input-3-d6c4a00a0e12>](https://localhost:8080/#) in <cell line: 96>()
     94 </policymap>""" 
     95 
---> 96 with open('/etc/ImageMagick-6/policy.xml', 'w') as f:
     97     f.write(s)
     98 

FileNotFoundError: [Errno 2] No such file or directory: '/etc/ImageMagick-6/policy.xml'

 
Can you please help with this error?

**Comment by crux82** [comment]
I fear there is a problem with COLAB itself

It seems it cannot install the dependencies

``! apt-get install libmagickwand-dev``

I fear it should be notified to COLAB itself...

**Comment by dadelani** [comment]
thanks for the reply.

**Comment by cyriltw** [comment]
I'm also running to this issue. @crux82 that's the issue, seems like it's not getting installed or being picked up properly.

**Comment by annadmitrieva** [comment]
I ran `! apt-get update` on colab before all other cells and everything worked

**Comment by crux82** [comment]
@annadmitrieva GREAT! This solved the issue. 

I updated the Python book.

@dadelani can you confirm that it is now working and close this issue? 

Thanks!

**Comment by dadelani** [comment]
@crux82 , yes, "! apt-get update" worked for me. 

Thank you so much @annadmitrieva and @crux82 .
