### ISSUE TITLE
Margin violation in every lines

### ISSUE THREAD

**Issue by smbslt3** [acl-org/aclpubcheck#57]
Hello all

I wrote my thesis with EMNLP 2023 version of Overleaf. And I used Colab version of ACLpubcheck. However, it says that all the lines in my paper exceed the margin. I did not change anything in the latex formatting of EMNLP 2023. And also didn't change nothing in the colab code.

To check, I downloaded the pdf of the Instructions for EMNLP 2023 Proceedings (https://www.overleaf.com/latex/templates/instructions-for-emnlp-2023-proceedings/scyjxmtnrskr) and ran the online pubcheck. The results were the same.

Is there a problem with aclpubcheck?

![image](https://github.com/acl-org/aclpubcheck/assets/41793074/a9c464ad-850e-41de-b580-6d780f682a88)

![image](https://github.com/acl-org/aclpubcheck/assets/41793074/dc374beb-105f-4057-b980-4f307a5e2383)

**Comment by crux82** [comment]
```aclpubcheck``` should be applied to camera-ready files. 

I just wanted to let you know that you generated the version to be submitted for review. 
Please, open the latex file and take a look at this row:

```
% Remove the "review" option to generate the final version.
\usepackage[review]{EMNLP2023}
```

I hope this helps you.

Bests

Danilo

**Comment by smbslt3** [comment]
@crux82 After remove `[review]`, it works properly. Great thanks!
