### ISSUE TITLE
Graphical User Interface

### ISSUE THREAD

**Issue by teelinsan** [acl-org/aclpubcheck#58]
Hi,
I made a minimal graphical user interface in gradio that wraps aclpubcheck [here the repo](https://github.com/teelinsan/aclpubcheck-gui).
If you think it might be useful, I can open a pull request to integrate the code for the GUI.
Thank you.

Andrea

**Comment by crux82** [comment]
Hi Andrea, 

this is great news. 
Only a suggestion: I used this GUI https://huggingface.co/spaces/teelinsan/aclpubcheck to check a malformed paper.

It seems to work and it found a page with a text out of the boundary. 
In this case, aclpubcheck should be able to show the page with the problem marked with a red box. 

Is it possible to show this image in the GUI?

Thank you again for your work!

Bests

Danilo

**Comment by teelinsan** [comment]
Hi Danilo,

Thank you for your feedback!
Yes, I think it is definitively possible since the output is HTML

I'll check out how to do it! 👀 

Andrea

**Comment by teelinsan** [comment]
Ok, fixed.
Now it shows also pages with problems marked with a red box :+1:

**Comment by crux82** [comment]
Thank you Andrea, I mentioned this useful version in the README file.
