### ISSUE TITLE
Hosted PubCheck?

### ISSUE THREAD

**Issue by ocramz** [acl-org/aclpubcheck#63]
Hi,
Would it be an option to host the tool somewhere on the web, and offer it as a service to the community?

Thank you,

**Comment by crux82** [comment]
Hi, 

did you consider these options?

https://github.com/acl-org/aclpubcheck#online-versions

Bests

Danilo

**Comment by ocramz** [comment]
@crux82 thank you, unfortunately the Colab version hangs while installing deps and the Huggingface one only displays an unhelpful "Error" icon in the middle of the UI.

**Comment by crux82** [comment]
@ocramz Can you try the Colav version now?

@teelinsan can you check the Huggingface one?

**Comment by teelinsan** [comment]
Looking into the issue of the version hosted on Huggingface 👀

**Comment by teelinsan** [comment]
Fixed the issue on the Huggingface version.
@ocramz you can also run a self-hosted version via docker from this repo https://github.com/teelinsan/aclpubcheck-gui
